Digiflow/Digiflow/urls.py
from django.contrib import admin
from django.urls import path, include

from api.urls import router
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('api/', include(router.urls)),
    path('api/', include('api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('', include('forum.urls', namespace='forum')),
    path('__debug__/', include('debug_toolbar.urls')),

]

Digiflow/api/urls.py
from django.urls import path, include
from rest_framework import routers

from .views import (
    TokenObtainPairView,
    QuestionApiView
)
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)
from rest_framework import routers
router = routers.DefaultRouter()


app_name = 'api'
urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('question_list', QuestionApiView.as_view(), name='question_list'),

]

from rest_framework.authtoken import views
urlpatterns += [
    path('api-token-auth/', views.obtain_auth_token)
]

Digiflow/forum/urls.py
from django.urls import path
from .views import *


app_name = 'forum'
# forum-question = home



urlpatterns = [

    path('<int:pk>/update/', QuestionUpdateView.as_view(), name="question-update"),
    path('<int:pk>/delete/', QuestionDeleteView.as_view(), name="question-delete"),

    path('add-friend/<int:pk>/', AddFriendRelationship, name='add-friend'),
    path('remove-friend/<int:pk>/', RemoveFriendRelationship, name='remove-friend'),

    path('register/', UserRegistrationView.as_view(), name="register"),
    path('login/', UserLoginView.as_view(), name="login"),
    path('login/submit/', ConnectAjax, name='login-submit'),
    path('tag/create/', TagCreateView.as_view(), name="tag-create"),
    path('tag/<str:slug>/', TagView.as_view(), name="tag"),
    path('question/<int:pk>/', QuestionDetailView.as_view(), name='questiondetail'),
    path('answer-create/<int:id>/', AnswerSubmit, name='answer-create'),
    path('question-create/', QuestionCreateView.as_view(), name='question-create'),
    path('question-vote/<int:pk>/', ChangeVoteQuestion, name="question-vote"),
    path('answer-vote/<int:pk>/', ChangeVoteAnswer, name="answer-vote"),
    path('createprofile', ProfileCreateView.as_view(), name="create-profile"),
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name="user-profile"),
    path('profile/<int:pk>/update', ProfileUpdateView.as_view(), name="user-profileupdate"),
    path('profileList', ProfileListView.as_view(), name="ajouter-amie"),

    path('following/<str:slug>', FollowingListOfUser.as_view(), name="following-list"),
    path('follower/<str:slug>', FollowerListOfUser.as_view(), name="follower-list"),

    path('', HomeView.as_view(), name="home"),
    path('list_question', QuestionListView.as_view(), name="forum-question"),
    path('logout', Logout, name="logout"),
    path('search-question', SearchQuestion, name="search-question"),

]

   
    

Digiflow/templates/site/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">

  <title>
      {% block head_title %}{% endblock %}
  </title>
  {% block extra_head %}
  {% endblock %}
   {% include "site/css.html" %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</head>
{% include "site/navbar.html" %}
<body>
<div class="mt-5 pt-5">
{% if messages %}
    {% for message in messages %}
    <div class="{{ message.tags }} alert-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
    {% endfor %}
{% endif %}
</div>

    <div class="row">
        <div class="col-10">
        {% block content %}
        {% endblock content %}
        </div>
        <div class="col-2">
            {% include "site/sidebar.html" %}
        </div>
    </div>
    {% block extra_body %}
    {% endblock %}
    {% include "site/footer.html" %}
    {% include "site/javascript.html" %}
    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

Digiflow/templates/site/css.html
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
<style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>

Digiflow/templates/site/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">


    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2022 Copyright:
      <a href="https://github.com/GaelleOGER/projetGroupe4" target="_blank"> ProjetGroup4 </a>
    </div>
    <!--/.Copyright-->

  </footer>

Digiflow/templates/site/javascript.html
<script crossOrigin="anonymous"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        src="https://code.jquery.com/jquery-3.3.1.slim.min.js">
</script>


<script>
        function menuToggle(){
            const toggleMenu = document.querySelector('.menu');
            toggleMenu.classList.toggle('active')
        }

</script>

Digiflow/templates/site/navbar.html
<nav class="navbar fixed-top justify-content navbar-expand-lg navbar-light scrolling-navbar" style="background-color: #e3f2fd;">
    <div class="container">
        <!-- Brand -->
        <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-target="#navbarSupportedContent" data-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>

        {% if user.is_authenticated %}
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ">
                <li class="nav-item active">
                    <a class="navbar-brand waves-effect" href="/">
                        <strong class="blue-text"> DigiFlow </strong>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="btn btn-outline-success " href="{% url 'forum:user-profile' pk=user.pk %}">
                        {{ request.user}}
                    </a>
                </li>

                <li class="nav-item  mx-1">
                    <a class="btn btn-success" href="{% url 'forum:question-create' %}">Poser une question</a>
                </li>
                <li class="nav-item  mx-1">
                    <a class="btn btn-danger float-right" href="{% url 'forum:logout' %}"> Logout</a>
                </li>
                  </ul>

                <div>
                    <form class="form-inline my-2 my-lg-0 ml-5" method="POST" action="{% url 'forum:search-question' %}">
                        {% csrf_token %}
                <input aria-label="Search" class="form-control mr-sm-2" placeholder="Chercher une question"
                       type="search" name="searched">
                <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit">Go</button>
            </form>
                </div>




            {% else %}
            <div class="row">
                <div class="nav-item"><a class="btn btn-success  mx-2" href="/login"> Login </a></div>
                <div class="nav-item"><a class="btn btn-primary  mx-2" href="/register"> Créer un compte </a></div>
            </div>

            {% endif %}

        </div>
    </div>
</nav>

Digiflow/templates/site/sidebar.html
<h5 class="mt-5">Questions par Tag</h5>
<ul>
    {% for each in tags %}
        <li>
            <span id="{{each.slug}}" class="tag-filter">{{ each.name }}</span>
        </li>
    {% endfor %}
</ul>
<div>
    <a class="btn btn-success" href="{% url 'forum:tag-create' %}">
    créer un tagg
    </a>
</div>