Digiflow/Digiflow/urls.py
from django.contrib import admin
from django.urls import path, include

from api.urls import router
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView

urlpatterns = [
    path('api/', include(router.urls)),
    path('api/', include('api.urls', namespace='api')),
    path('api-auth/', include('rest_framework.urls')),
    path('admin/', admin.site.urls),
    path('', include('forum.urls', namespace='forum')),
    path('__debug__/', include('debug_toolbar.urls')),

]

Digiflow/api/urls.py
from django.urls import path, include
from rest_framework import routers

from .views import (
    TokenObtainPairView,
    QuestionApiView
)
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)
from rest_framework import routers
router = routers.DefaultRouter()


app_name = 'api'
urlpatterns = [
    path('token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path('question_list', QuestionApiView.as_view(), name='question_list'),

]

from rest_framework.authtoken import views
urlpatterns += [
    path('api-token-auth/', views.obtain_auth_token)
]

Digiflow/forum/urls.py
from django.urls import path
from .views import *


app_name = 'forum'
# forum-question = home



urlpatterns = [

    path('<int:pk>/update/', QuestionUpdateView.as_view(), name="question-update"),
    path('<int:pk>/delete/', QuestionDeleteView.as_view(), name="question-delete"),

    path('add-friend/<int:pk>/', AddFriendRelationship, name='add-friend'),
    path('remove-friend/<int:pk>/', RemoveFriendRelationship, name='remove-friend'),

    path('register/', UserRegistrationView.as_view(), name="register"),
    path('login/', UserLoginView.as_view(), name="login"),
    path('login/submit/', ConnectAjax, name='login-submit'),
    path('tag/create/', TagCreateView.as_view(), name="tag-create"),
    path('tag/<str:slug>/', TagView.as_view(), name="tag"),
    path('question/<int:pk>/', QuestionDetailView.as_view(), name='questiondetail'),
    path('answer-create/<int:id>/', AnswerSubmit, name='answer-create'),
    path('question-create/', QuestionCreateView.as_view(), name='question-create'),
    path('question-vote/<int:pk>/', ChangeVoteQuestion, name="question-vote"),
    path('answer-vote/<int:pk>/', ChangeVoteAnswer, name="answer-vote"),
    path('createprofile', ProfileCreateView.as_view(), name="create-profile"),
    path('profile/<int:pk>/', ProfileDetailView.as_view(), name="user-profile"),
    path('profile/<int:pk>/update', ProfileUpdateView.as_view(), name="user-profileupdate"),
    path('profileList', ProfileListView.as_view(), name="ajouter-amie"),

    path('following/<str:slug>', FollowingListOfUser.as_view(), name="following-list"),
    path('follower/<str:slug>', FollowerListOfUser.as_view(), name="follower-list"),

    path('', HomeView.as_view(), name="home"),
    path('list_question', QuestionListView.as_view(), name="forum-question"),
    path('logout', Logout, name="logout"),
    path('search-question', SearchQuestion, name="search-question"),

]

   
    

Digiflow/forum/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Tag, Answer, Question


class UserRegistrationForm(UserCreationForm):
    email = forms.EmailField(max_length=50, required=True)
    username = forms.CharField(max_length=50, required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.fields['email'] = forms.EmailField(max_length=150)
        self.fields['username'] = forms.CharField(max_length=100)
        self.fields['password1'] = forms.CharField(
            strip=False,
            widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
            help_text='',
        )
        self.fields['password2'] = forms.CharField(
            strip=False,
            widget=forms.PasswordInput(attrs={'autocomplete': 'new-password'}),
            help_text='',
        )


class UserLoginForm(forms.Form):
    username = forms.CharField(label="Nom  d'utilisateur",
                               widget=forms.TextInput(attrs={'placeholder': "Entrer votre nom d'utilisateur"}),
                               max_length=50, required=True)
    password = forms.CharField(label='Mot de passe', widget=forms.PasswordInput(attrs={'placeholder': 'Entrer mot de '
                                                                                                      'passe'}),
                               max_length=50, min_length=6, required=True)

    class Meta:
        model = User
        fields = ['username', 'password']


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ['name']


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['body']

    def __init__(self, *args, **kwargs):
        super(AnswerForm, self).__init__(*args, **kwargs)
        self.fields['body'] = forms.CharField(max_length=1500, required=True,
                                              widget=forms.Textarea(attrs={'class': 'form-control'}))


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['title', 'body']

        title = forms.CharField(max_length=150, required=True,
                                widget=forms.TextInput(attrs={'class': 'form-control'}))
        body = forms.CharField(max_length=1500, required=True,
                               widget=forms.Textarea(attrs={'class': 'form-control'}))

Digiflow/forum/views.py
# Create your views here.
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, View, DeleteView
from django.contrib.auth.models import User
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.http import JsonResponse
from django.urls import reverse, reverse_lazy
from django.views import View

from .forms import UserRegistrationForm, UserLoginForm, TagForm, AnswerForm, QuestionForm

from django.contrib.auth import logout
from .models import *

from rest_framework.permissions import AllowAny
from rest_framework.views import APIView
from rest_framework.generics import ListAPIView
from api.serializers import TagFilterSlugModelSerializer

# Home


class HomeView(ListView):
    paginate_by = 5
    model = Question
    template_name = "home.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        #afficher les 10 premiers elements
        context['tags'] = Tag.objects.all()[:10]
        context['questions'] = Question.objects.all()
        context['number'] = len(Question.objects.all())
        return context


# PROFILE
"""def profile(request):
    profile = Profile.objects.all()

    return render(request,'profile.html', {'profile':profile})"""



class ProfileCreateView(CreateView):
    model = Profile
    template_name = "create_profile.html"
    fields = ['first_name', 'last_name', 'image', 'bio']

    """def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)"""


class ProfileDetailView(DetailView):
    model = Profile
    template_name = "profile.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        auth = self.request.user
        context['amies'] = auth.userprofile.friendlist.count()
        context['question'] = Question.objects.filter(user=self.kwargs['pk']).order_by('created_at')
        context['answer'] = Answer.objects.filter(user=self.kwargs['pk']).order_by('created_at')
        context['date_joind'] = auth.date_joined
        return context


class ProfileListView(ListView):
    model = Profile
    template_name = "profile_list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        id_auth = self.request.user.id
        context['profile_list'] = Profile.objects.exclude(user__id=id_auth)
        return context


"""class AjouteAmieCreateView(CreateView):
    model = Friendship
    template_name = "profile_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = Profile.objects.all()
        return context"""


class ProfileUpdateView(UpdateView):
    model = Profile
    template_name = 'profile_update.html'
    fields = ['first_name', 'last_name', 'bio', 'point']

    """def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)"""


# FRIEND


def AddFriendRelationship(request, *args,**kwargs):

    priorURL = request.META.get('HTTP_REFERER')
    object = Profile.objects.get(pk=kwargs['pk'])
    friend = Friend.objects.create(
        profile=request.user.userprofile,
        friend=object.user,
    )
    object.waitinglist.add(request.user)

    return redirect(priorURL)


def RemoveFriendRelationship(request, *args, **kwargs):
    priorURL = request.META.get('HTTP_REFERER')
    qs1 = Friend.objects.get(friend=User.objects.get(pk=kwargs['pk']), profile=request.user.userprofile)
    qs1.delete()
    qs2 = Friend.objects.get(friend=request.user, profile=User.objects.get(pk=kwargs['pk']))
    qs2.delete()
    url = reverse_lazy('forum:ajouter-amie')
    return redirect(priorURL)


# def AddAmie(request, *args, **kwargs):
#     priorURL = request.META.get('HTTP_REFERER')
#     user_cliquer = User.objects.get(id=kwargs['pk'])
#     id_user = request.user
#     print(user_cliquer.userprofile.friendlist)
#     print(type(user_cliquer))
#     print(id_user)
#     if user_cliquer in request.user.userprofile.friendlist:
#         request.user.userprofile.friendlist.remove(user_cliquer)
#         request.user.userprofile.save()
#     else:
#         request.user.userprofile.friendlist.add(user_cliquer)
#         request.user.userprofile.save()
#
#     return redirect(priorURL)


# QUESTION
class QuestionDetailView(DetailView):
    model = Question
    template_name = 'question_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = AnswerForm()
        context['answer'] = Answer.objects.filter(question__pk=self.kwargs['pk'])
        return context


def AnswerSubmit(request, *args, **kwargs):
    priorURL = request.META.get('HTTP_REFERER')
    if request.method == "POST":
        form = AnswerForm(request.POST or None)
        if form.is_valid():
            form.instance.question = Question.objects.get(id=kwargs['id'])
            form.instance.user = request.user
            form.save()  # On sauvegarde le formulaire
            messages.success(request, 'réponse publié')
            return redirect(priorURL)
    else:
        messages.error(request, 'réponse non publié')
        form = AnswerForm()

    return render(request, 'question_detail.html', context={"form": form})


class QuestionCreateView(CreateView):
    model = Question
    template_name = 'question-create.html'
    fields = ['title', 'body', 'tags']

    def form_valid(self, form):

        # ici la logique de point
        if self.request.user.userprofile.point != 0:
            form.instance.user = self.request.user
            self.request.user.userprofile.point -= 1
            self.request.user.userprofile.save()
            messages.success(self.request, "Votre question a bien été envoyé")
        else:
            messages.error(self.request, "Votre question n'a pas pu être envoyée, votre fomulaire n'est pas bon")
        return super().form_valid(form)


class QuestionListView(ListView):
    paginate_by = 5
    model = Question
    template_name = "landing.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['questions'] = Question.objects.all()
        dateFormat = Question.created_at
        return context


class QuestionUpdateView(UpdateView):
    model = Question
    template_name = "question_update.html"
    fields = ['title', 'body']
    success_url = reverse_lazy('forum:forum-question')

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class QuestionDeleteView(DeleteView):
    model = Question
    template_name = "question_delete.html"

    def get_success_url(self):
        url = reverse_lazy('forum:forum-question')
        return redirect(url)


# nous avons deux vue qui nous permettent de défenir si c 'est une question ou une réponse
# donc deux url et relatif
# pour les question reverse d'url dans la template avec l'id de la question
# et la meme chose pour les reponse


def ChangeVoteQuestion(request, *args, **kwargs):
    priorURL = request.META.get('HTTP_REFERER')
    question = Question.objects.get(id=kwargs['pk'])
    toi = request.user

    if toi == question.user:
        # rajouter le message comm quoi on ne peut pas voté sa propre question
        return redirect(priorURL)
    if toi in question.questionvote.profile.all():
        question.questionvote.profile.remove(toi)
        request.user.userprofile.point -= 1
        request.user.userprofile.save()
    else:
        question.questionvote.profile.add(toi)
        request.user.userprofile.point += 1
        request.user.userprofile.save()
        return redirect(priorURL)
    return redirect(priorURL)


def ChangeVoteAnswer(request, *args, **kwargs):
    priorURL = request.META.get('HTTP_REFERER')
    answer = Answer.objects.get(id=kwargs['pk'])
    toi = request.user

    if toi == answer.user:
        # rajouter le message comm quoi on ne peut pas voté sa propre question
        return redirect(priorURL)
    if toi in answer.answervote.profile.all():
        answer.answervote.profile.remove(toi)
        answer.user.userprofile.point -= 1
        answer.user.userprofile.save()
    else:
        answer.answervote.profile.add(toi)
        answer.user.userprofile.point += 1
        answer.user.userprofile.save()
    return redirect(priorURL)


class FollowingListOfUser(DetailView):
    model = Profile
    template_name = 'following.html'


class FollowerListOfUser(DetailView):
    model = Profile
    template_name = 'follower.html'  # object.follower.all, object.following.all dans template in for loop


class UserRegistrationView(View):
    template_name = "user_registration_form.html"

    def get(self, request):
        context = {}
        context['form'] = UserRegistrationForm()
        return render(request, self.template_name, context)

    def post(self, request):
        form = UserRegistrationForm(request.POST or None)
        if form.is_valid():
            # do something
            pass
        username = request.POST['username']
        email = request.POST['email']
        password1 = request.POST['password1']
        password2 = request.POST['password2']

        context = {}
        context['form'] = UserRegistrationForm()
        if username == '':
            messages.error(request, "Vous n'avez pas rempli de userName")
            return render(request, self.template_name, context)
        elif (password1 == '') | (password2 == ''):
            messages.error(request, "Vous n'avez pas rempli les champs de password")
            return render(request, self.template_name, context)
        elif password1 != password2:
            messages.error(request, "Les deux password sont différents")

Digiflow/forum/templates/create_profile.html
{% include "css.html" %}
{% load static %}
{% load crispy_forms_tags %}
<title>Create profile</title>


<body>
<form method="post">
    <div>
    {% csrf_token %}
    {{ crispy form}}
    <button type="submit" class="btn btn-success mt-3" value="Create">Envoyer</button>
    </div>
</form>
<a href="{% url 'forum:user-profile' pk=object.pk %}" >
<button class="btn btn-danger mt-3">Cancel</button>
</a>
</body>

Digiflow/forum/templates/home.html
{% extends "site/base.html" %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}


<div class="row" id="main-question-filter-container">
    <div class="col-lg-10 mx-auto mb-4">
        <h1 class="top-l-sep">Bienvenue</h1>
        <div class="section-title text-center ">
            <h4 class="top-c-sep">Liste des questions</h4>
            <p class="mb-30 ff-montserrat">Total de questions : {{number}}</p>
        </div>
    </div>
</div>
<div class="row m-4" id="main-question-container">
    {% for each in questions %}
    <div class="col-12 p-3">
        <div class="card" style="width:18 rem;">
            <div class="card-body">
                <span class="badge badge-info tag-filter float-end" id="{{each.tags.slug}}">
                    {{ each.tags.name }}</span>
                <h5 class="card-title">{{each.title}}</h5>
                <h5 class="badge badge-success">{{each.questionvote.profile.count}}</h5>
                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                    <a href="{% url 'forum:questiondetail' pk=each.pk %}" class="btn btn-primary">Lire plus</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}


</div>
{% endblock content %}
<link rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css"      integrity="sha256-3sPp8BkKUE7QyPSl6VfBByBroQbKxKG7tsusY2mhbVY=" crossorigin="anonymous"/>

{% block extra_scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
<script>
console.log("Dans le script")
$('.tag-filter').click(function(e) {
        console.log("Dans le script2")
        e.preventDefault()
        var crypto = window.localStorage.getItem('access');
        var wrapperHeader = document.getElementById('main-question-filter-container')
        var wrapper = document.getElementById('main-question-container')
        wrapper.innerHTML = ``
        wrapperHeader.innerHTML = ``
        console.log("Dans le script3 "+ this.id)
        var url = '/tag/' + this.id + '/'
        fetch(url, {'content-type': 'application/json'})
        .then((resp) => resp.json())
        .then(function(data){
                    console.log("Dans le script")
                    console.log(data)

        var tagName = `${data[0].tags.name}`
            wrapperHeader.innerHTML += `
             <div class="col-lg-10 mx-auto mb-4">
                    <div class="section-title text-center ">
                        <h3 class="top-c-sep">QUESTIONS POUR # ${tagName}</h3>
<p class="mb-30 ff-montserrat">Total de questions : ${data.length}</p>
                    </div>
                </div>
            </div>
            `
            console.log('Data:', data)
            var list = data
            for (var i in list){

                var pk = `${list[i].pk}`
                var title = `${list[i].title}`
                var body = `${list[i].body}`
                var tags = `${list[i].tags.name}`
                var tagslug = `${list[i].tags.slug}`
                var item = ` <div class="col-12 p-3">
                                <div class="card" style="width:18 rem;">
                                    <div class="card-body">
                                        <span class="badge badge-info float-end" id="${tagslug}">
                                        ${tags}
                                        </span>

                                        <h5 class="card-title">${title}</h5>
                                        <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                            <a href="/question/${pk}/" class="btn btn-primary">Lire plus</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                `
                wrapper.innerHTML += item
            }
            console.log("Dans le script4")},
        )},

);


</script>
{% endblock %}

Digiflow/forum/templates/profile.html
{% extends "site/base.html" %}

{% load static %}


{% block content %}

<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
    <div class="card p-4">
        <div class=" image d-flex flex-column justify-content-center align-items-center">
            <button class="btnPer btn-secondary"> <img src="https://i.imgur.com/wvxPV9S.png" height="100" width="100" /></button>
            <span class="name mt-3">{{object.first_name}} {{object.last_name}}  </span>
            <span class="idd">Points: {{object.points}} </span>
            <div class="d-flex flex-row justify-content-center align-items-center mt-3">
                <span class="number">{{amies}}
                    <span class="follow">Amies</span>
                    <a href="{% url 'forum:ajouter-amie' %}">
                    <i class="fa fa-user-plus"></i>
                    </a>
                </span>
            </div>
             {% if request.user == user %}
            <div class="links">
                <a href="#" class="btn btn-sm btn-primary">Update Profile</a>
            </div>
            {% endif %}


            <div class="button">
                <a href="{% url 'forum:following-list' profile.slug %}" >
                    <button class="btn1">Following</button>
                </a>
             </div>

            <div class="button">
                <a href="{% url 'forum:follower-list' profile.slug %}" >
                    <button class="btn1">Followers</button>
                </a>
             </div>

            <div class="button">
                <a href="{% url 'forum:question-create' %}" >
                    <button class="btn1">J'ai un question</button>
                </a>
             </div>

            <div class="button">
                <a href="{% url 'forum:forum-question' %}" >
                    <button class="btn1"> Landing </button>
                </a>
             </div>
            <div class=" d-flex mt-2">
                <a href="{% url 'forum:user-profileupdate' pk=object.pk %}" >
                    <button class="btn1">Edit Profile</button>
                </a>
             </div>
            <div class="text mt-3"> <span>Bio: {{object.bio}}</span> </div>
            <div class="gap-3 mt-3 icons d-flex flex-row justify-content-center align-items-center"> <span><i class="fa fa-twitter"></i></span> <span><i class="fa fa-facebook-f"></i></span> <span><i class="fa fa-instagram"></i></span> <span><i class="fa fa-linkedin"></i></span> </div>
            <div class=" px-2 rounded mt-4 date "> <span class="join">{{date_joind}}</span> </div>

        </div>
    </div>
</div>


<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">
    <h3>DERNIERE ACTIVITE</h3>
</div>

<div class="container mt-4 mb-4 p-3 d-flex justify-content-center">

    {% for each in question %}

    <div class="row p-3">
        <div class="card2 p-4"> <p><strong>Q</strong></p></div>
        <div class="card p-4"> <p>  {{each.title}} {{each.created_at}}</p></div>
        <div class="card2 p-4"> <p>{{each.total_votes}}</p></div>
    {% endfor %}
    </div>

    {% for each in answer %}
    <div class="row p-3">
    <div class="card2 p-4"> <p><strong>R</strong></p></div>
    <div class="card p-4"> <p> {{each.body}} {{each.created_at}}</p></div>
    <div class="card2 p-4"> <p>{{each.total_votes}}</p></div>
    {% endfor %}
</div>
</div>

{% endblock %}

Digiflow/forum/templates/profile_update.html
{% extends "site/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
    <title>Update profile</title>

<body>
<form method="post">
    <div>
    {% csrf_token %}

    {% crispy form %}
        <a href="{% url 'forum:user-profile' pk=object.pk %}" >
<button class="btn btn-danger mt-3">Cancel</button>
</a>
    <button type="submit" class="btn btn-success mt-3 ml-2" >Envoyer</button>
</div>
</form>

</body>
{% endblock content %}

Digiflow/forum/templates/question-create.html
{% extends "site/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<!--ouverture de la ligne-->
<div class="row m-4">
    <div class="col-6">
        <form method="post">
    <div>
    {% csrf_token %}
    {% crispy form %}
      <button class="btn btn-danger mt-3">Cancel</button>
    <button type="submit" class="btn btn-success mt-3">Envoyer</button>
        </div>
</form>
<!--{{form}}-->
    </div>
</div>
<!--fermeture de la ligne-->

{% endblock content %}

Digiflow/forum/templates/question_detail.html
{% extends "site/base.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div class="row">
    <div class="col-12">
        <div class="card  shadow rounded">
            <div class="card-body">
                <h1 class=""><strong>{{object.title}}</strong></h1>
                <p>{{ object.body }}</p>
                <p>{{ object.created_at }}</p>
                <h5>nombre de vote</h5>
                <span class="badge badge-success">{{object.questionvote.profile.count}}</span>
                {% if request.user in object.questionvote.profile.all %}
                <a class="badge badge-danger" href="{% url 'forum:question-vote' pk=object.pk %}">unvote</a>
                {% else %}
                <a class="badge badge-dark" href="{% url 'forum:question-vote' pk=object.pk %}">vote</a>
                {% endif %}
            </div>
            <div class="card-footer">
                <a class="btn btn-danger" href="{% url 'forum:home' %}">
                    retour au questions
                </a>
            </div>
        </div>
    </div>
</div>
<div class="row">
    {% for each in object.questionanswer.all %}
    <div class="col-12 mt-3 row">
        <div class="col-2 ">
            <div class="card mx-3 shadow rounded">
                <p class="card-body" style="font-size: calc(1.5rem + 2.3vw); font-weight: 900;">R</p>
            </div>
        </div>
        <div class="col-10 ">
            <div class="card mr-3 shadow rounded">
                <div class="card-body">
                    <p>{{ each.body }}</p>
                    <div>
                        <h5>nombre de vote</h5>
                        <span class="badge badge-success">{{each.answervote.profile.count}}</span>
                        <a href="{% url 'forum:answer-vote' pk=each.pk %}">vote</a>
                    </div>
                    <span>{{ each.created_at|date:"D d M Y" }}</span>
                </div>
            </div>
            </div>
        </div>

    {% endfor %}
</div>

<div class="card m-3">
    <div class="card-body">
        {% if request.user.userprofile.point != 0 %}
    <div class="row m-1">
        <div class="col-12">
            <h4 class="mb-4 "> Veuillez créer une nouvelle réponse </h4>
            <form action="{% url 'forum:answer-create' id=object.id %}" method="POST">
                <div>
                    {% csrf_token %}
                    {% crispy form %}

                    <button class="btn btn-success mt-3 ml-3" type="submit"> Envoyer</button>
                </div>
            </form>
        </div>
    </div>

{% else %}
<div class="card">
    <div class="card-body">

        <h4 class="text-danger">Vous n'avez pas assez de point pou répondre à la question!!</h4>
    </div>
</div>
{% endif %}

    </div>
    </div>



{% endblock content %}

<link crossorigin="anonymous"
      href="https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css"
      integrity="sha256-3sPp8BkKUE7QyPSl6VfBByBroQbKxKG7tsusY2mhbVY=" rel="stylesheet"/>

{% block extra_scripts %}
<script crossorigin="anonymous"
        integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
console.log("Dans le script")
$('.tag-filter').click(function(e) {
        console.log("Dans le script2")
        e.preventDefault()
        var crypto = window.localStorage.getItem('access');
        var wrapper = document.getElementById('main-question-container')
        wrapper.innerHTML = ``
        console.log("Dans le script3 "+ this.id)
        var url = '/tag/' + this.id + '/'
        fetch(url, {'content-type': 'application/json', Authorization: 'Bearer ' + crypto})
        .then((resp) => resp.json())
        .then(function(data){
            console.log('Data:', data)
            var list = data
            for (var i in list){

                var pk = `${list[i].pk}`
                var title = `${list[i].title}`
                var body = `${list[i].body}`
                var tags = `${list[i].tags.name}`
                var tagslug = `${list[i].tags.slug}`
                var item = `                    <div class="col-12 p-3">
                           <span class="badge badge-info tag" style="position:relative;top: 30px;left: 10px;z-index: 1000" id="${tagslug}">
                                    ${tags}
                                </span>
                        <div class="card">
                            <div class="card-body">



                                <h5 class="card-title">${title}</h5>
                                <div class="d-grid gap-2 d-md-flex justify-content-md-end">
                                    <a href="/question/${pk}/" class="btn btn-primary">Lire plus</a>
                                </div>
                            </div>
                        </div>
                    </div>
                `
                wrapper.innerHTML += item
            }
            console.log("Dans le script4")},
        )},

);


</script>
{% endblock %}

Digiflow/forum/templates/tag.html
{% extends "site/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

<h5 class="mt-5">Questions par Tag</h5>
<ul>
    {% for each in tags %}
        <li>
            <span id="{{each.slug}}" class="tag-filter">{{ each.name }}</span>
        </li>
    {% endfor %}
</ul>
<div>
    <a class="btn btn-success" href="{% url 'forum:tag-create' %}">
    créer un tagg
    </a>
</div>

{% endblock content %}